### PR TITLE
WIP: Improve skill installation

### PR DESCRIPTION
**Pull request by maxbachmann**
Changes:
the skill store json is saved in a property and only updated:
- when onStart is called
- once per hour when skills are updated
- when updates for a specific skill are searched via route('/<skillName>/checkUpdate/') in the Web interface
- skills installed from zip files on skills.projectalice.io
- github auth removed

-> skill store will load a lot faster since it directly accesses the cached property (it is not a big deal when the skill store is outdated by up to 60min)
-> no github token has to be created anymore
-> installing skills works faster and is less error prone

### CODE REVIEW

**Comment by maxbachmann** [comment]
@Psychokiller1888 hm so you would like a skill dev to install from his own repo for testing?

**Comment by Psychokiller1888** [comment]
More like to push the PR directly. Skill dev don't need the repo to test, Alice accepts not published skills if dev mode is on

**Comment by maxbachmann** [comment]
hm I would add this functionality to the skill kit, which he should already use before to validate his skill

**Comment by Psychokiller1888** [comment]
Yeah, and skill kit should be integrated into the interface, dev section :)

**Comment by maxbachmann** [comment]
ah ok. I will keep it and update the description

**Comment by maxbachmann** [comment]
I will finish this next weekend

**Comment by Psychokiller1888** [comment]
First todo is done, second is a let it be for now

**Comment by maxbachmann** [comment]
the second todo is already implemented here, but not tested yet

**Comment by maxbachmann** [comment]
should be reopened when the new approach is ready

**Pull request closed without merging**
