### PR TITLE
Vosk ASR support

### PR DESCRIPTION
**Pull request by nshmyrev**
[Vosk](https://alphacephei.com/vosk) is an offline ASR library supporting 20+ languages on RPi. It would be nice to support in Alice.

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Wow, that's awesome! Thank you for the PR!!

**Comment by Psychokiller1888** [comment]
Sorry, had to manually merge onto rc3, but I credited your contribution here: https://github.com/project-alice-assistant/ProjectAlice/commit/59a47dc8d79d30a1bf8f57f50907bd1668f06f5f

**Comment by nshmyrev** [comment]
Thanks a lot! Sorry for confusion with the branch!

**Comment by Psychokiller1888** [comment]
Not an issue!

**Comment by Psychokiller1888** [comment]
@nshmyrev This is a pre implementation right? It just cannot work, there's no model downloading etc etc

**Pull request closed without merging**
