### PR TITLE
Translation for pt_br

### PR DESCRIPTION
**Pull request by overcyber**
##### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] New feature
- [ ] Refactoring
- [x] Translation 
- [ ] Other, please describe:

##### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

##### The PR fulfills these requirements:

- [ ] When resolving/implementing a specific issue, it's referenced in the PR's title (e.g. `fix #xxx` or `implement #xxx`, where "xxx" is the issue number)
- [ ] You have tested your changes on the branch you wish to merge
- [ ] The changes are working

If adding a **new feature**, the PR's description includes:

- [ ] The reason for this new feature to be added
- [ ] The use of this new feature
- [ ] If available, a link to an existing feature request ticket

### CODE REVIEW

**Review by Psychokiller1888 — CHANGES_REQUESTED** [review]
Why all the deleted files?? Please revert before we merge

**Comment by Psychokiller1888** [comment]
Better, thanks! Now missing manager/WebUIManager ;-)

**Review by overcyber — COMMENTED** [review]
correction of deleted files

**Review by Psychokiller1888 — APPROVED** [review]
Looks ok to me

**Pull request closed without merging**
